version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0

jobs:
  build_and_test:
    docker:
      — image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      — checkout
      - run: npm install
 
      — run: npm test
  deploy:
  - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          dockerfile: Dockerfile
          path: .
          region: eu-west-2
          repo: nameofrepo
          tag: latest