version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
  node: circleci/node@5.0.2

jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run Unit Tests
          command: |
            ./node_modules/mocha/bin/mocha test/ --reporter mochawesome --reporter-options reportDir=test-results,reportFilename=test-results
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          dockerfile: Dockerfile
          path: .
          region: eu-west-2
          repo: nameofrepo
          tag: latest
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test
      - build_docker_image
      - deploy