version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    docker:
      — image: circleci/node:7.10
    working_directory: ~/repo
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run build
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy:
    steps:
      - attach_workspace:
      - aws-ecr/build-and-push-image:
          filters:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          dockerfile: Dockerfile
          path: .
          region: eu-west-2
          repo: nameofrepo
          tag: latest